# NOTE: Git abbr
abbr ga 'git add'
abbr gaa 'git add --all'
abbr gb 'git branch'
abbr gcl 'git clone'
abbr gcm 'git commit -m'
abbr gco 'git checkout'
abbr gcob 'git checkout -b'
abbr gcod 'git checkout devel'
abbr gcom 'git checkout master'
abbr gdi 'git diff'
abbr gin 'git init'
abbr gm 'git merge'
abbr gp 'git push'
abbr gp! 'git push -f'
abbr gps 'git push --set-upstream origin'
abbr gpl 'git pull'
abbr gpl! 'git pull -f'
abbr gra 'git remote add origin'
abbr gre 'git rebase'
abbr grm 'git rm'
abbr grmc 'git rm --cached'
abbr gs 'git status'
abbr gss 'git status --short'
abbr gsu 'git submodule update --remote'
abbr gsua 'git submodule add'
abbr gsur 'git submodule update --recursive'
abbr gsuri 'git submodule update --recursive --init'
abbr gst 'git stash'
abbr gwch 'git whatchanged -p --abbrev-commit --pretty=medium'
